import {
  Bot,
  Braces,
  Cloud,
  Code2,
  Cpu,
  Database,
  GitBranch,
  Globe2,
  KeyRound,
  Network,
  Shield,
  Terminal,
  Wrench,
} from "lucide-react";
import { type Category, type CheatSheet, type UtilityTool } from "@/lib/types";

export const techTags = [
  "Python",
  "JavaScript",
  "Git",
  "Linux",
  "SQL",
  "Docker",
  "Bash",
  "Nmap",
  "Burp Suite",
  "Wireshark",
  "React",
];

export const categories: Category[] = [
  { name: "Programming", slug: "programming", description: "Languages, patterns, debugging, and APIs.", count: 132, icon: Code2 },
  { name: "Cybersecurity", slug: "cybersecurity", description: "Pentesting, appsec, blue-team, and references.", count: 118, icon: Shield },
  { name: "Linux", slug: "linux", description: "Shell, permissions, processes, networking, and services.", count: 64, icon: Terminal },
  { name: "Networking", slug: "networking", description: "Protocols, ports, DNS, packets, and troubleshooting.", count: 52, icon: Network },
  { name: "Cloud", slug: "cloud", description: "AWS, Azure, GCP, containers, and serverless.", count: 48, icon: Cloud },
  { name: "DevOps", slug: "devops", description: "CI/CD, Git, Docker, Kubernetes, and observability.", count: 45, icon: GitBranch },
  { name: "Databases", slug: "databases", description: "SQL, NoSQL, indexing, transactions, and tuning.", count: 37, icon: Database },
  { name: "AI", slug: "ai", description: "Prompting, model APIs, evals, RAG, and agents.", count: 28, icon: Bot },
];

export const utilityTools: UtilityTool[] = [
  { slug: "json-formatter", name: "JSON Formatter", description: "Format, validate, and minify JSON safely in-browser.", category: "Format" },
  { slug: "base64", name: "Base64 Encoder/Decoder", description: "Encode and decode UTF-8 text without network requests.", category: "Encode" },
  { slug: "url-encoder", name: "URL Encoder", description: "Encode and decode URI components for query strings.", category: "Encode" },
  { slug: "regex-tester", name: "Regex Tester", description: "Test JavaScript regular expressions against sample text.", category: "Preview" },
  { slug: "hash-generator", name: "Hash Generator", description: "Generate SHA-256 digests for strings using Web Crypto.", category: "Security" },
  { slug: "uuid-generator", name: "UUID Generator", description: "Generate RFC 4122 random UUIDs instantly.", category: "Generate" },
  { slug: "jwt-decoder", name: "JWT Decoder", description: "Decode JWT headers and payloads without verification.", category: "Security" },
  { slug: "password-generator", name: "Password Generator", description: "Create strong passwords with adjustable length.", category: "Security" },
  { slug: "markdown-preview", name: "Markdown Preview", description: "Preview markdown headings, lists, code, and links.", category: "Preview" },
  { slug: "color-picker", name: "Color Picker", description: "Convert and preview HEX, RGB, and HSL colors.", category: "Design" },
];

const commonQuiz = (topic: string) => [
  {
    question: `What is the safest way to learn ${topic} commands?`,
    options: ["Run examples blindly", "Read context, test in a sandbox, then apply", "Disable logs"],
    answer: "Read context, test in a sandbox, then apply",
  },
  {
    question: "Which habit improves long-term retention?",
    options: ["Copying snippets only", "Practicing small variations", "Skipping errors"],
    answer: "Practicing small variations",
  },
];

export const cheatSheets: CheatSheet[] = [
  {
    slug: "python-essentials",
    title: "Python Essentials",
    category: "Programming",
    description: "Core syntax, data structures, comprehensions, files, virtual environments, and defensive scripting patterns.",
    tags: ["Python", "Programming", "Automation"],
    difficulty: "Beginner",
    updated: "2026-06-18",
    related: ["javascript-modern", "sql-queries", "bash-linux"],
    sections: [
      {
        title: "Data Structures",
        description: "Use clear literals and comprehensions for readable transformations.",
        language: "python",
        code: "users = [{'name': 'Ada', 'active': True}, {'name': 'Linus', 'active': False}]\nactive_names = [user['name'] for user in users if user['active']]\nlookup = {name.lower(): name for name in active_names}",
        tips: ["Prefer explicit names over clever one-liners.", "Guard file and network operations with exceptions.", "Use virtual environments per project."],
      },
      {
        title: "Safe CLI Script",
        description: "Build command-line tools that validate input and fail clearly.",
        language: "python",
        code: "from argparse import ArgumentParser\n\nparser = ArgumentParser(description='Summarize a text file')\nparser.add_argument('path')\nargs = parser.parse_args()\n\nwith open(args.path, encoding='utf-8') as file:\n    print(len(file.read().split()), 'words')",
        tips: ["Avoid shell=True unless absolutely required.", "Treat external input as untrusted.", "Log enough context to debug failures."],
      },
    ],
    quiz: commonQuiz("Python"),
  },
  {
    slug: "javascript-modern",
    title: "Modern JavaScript",
    category: "Programming",
    description: "ES modules, async patterns, DOM safety, array utilities, and browser APIs.",
    tags: ["JavaScript", "Frontend", "Node"],
    difficulty: "Intermediate",
    updated: "2026-06-21",
    related: ["react-hooks", "json-security", "regex-reference"],
    sections: [
      {
        title: "Async Workflow",
        description: "Wrap fetch calls with explicit error handling and predictable return shapes.",
        language: "ts",
        code: "export async function getJson<T>(url: string): Promise<T> {\n  const response = await fetch(url, { headers: { accept: 'application/json' } });\n  if (!response.ok) throw new Error(`Request failed: ${response.status}`);\n  return response.json() as Promise<T>;\n}",
        tips: ["Use AbortController for cancellable UI requests.", "Validate untrusted API data before rendering.", "Prefer textContent over innerHTML."],
      },
    ],
    quiz: commonQuiz("JavaScript"),
  },
  {
    slug: "react-hooks",
    title: "React Hooks",
    category: "Programming",
    description: "State, effects, memoization, custom hooks, and resilient component boundaries.",
    tags: ["React", "Hooks", "UI"],
    difficulty: "Intermediate",
    updated: "2026-06-25",
    related: ["javascript-modern", "ai-prompting", "git-workflows"],
    sections: [
      {
        title: "Custom Hook",
        description: "Extract stateful behavior without hiding data flow.",
        language: "tsx",
        code: "function useLocalValue(key: string, fallback: string) {\n  const [value, setValue] = useState(fallback);\n  useEffect(() => {\n    const saved = localStorage.getItem(key);\n    if (saved) setValue(saved);\n  }, [key]);\n  return [value, setValue] as const;\n}",
        tips: ["Keep dependency arrays honest.", "Move expensive work out of render.", "Prefer composition over prop drilling."],
      },
    ],
    quiz: commonQuiz("React"),
  },
  {
    slug: "bash-linux",
    title: "Linux Commands",
    category: "Linux",
    description: "Navigation, permissions, processes, services, archives, pipes, and safe shell practices.",
    tags: ["Linux", "Bash", "Terminal"],
    difficulty: "Beginner",
    updated: "2026-06-30",
    related: ["nmap-network-scanning", "docker-compose", "common-ports"],
    sections: [
      {
        title: "Find and Inspect",
        description: "Search files, inspect processes, and monitor ports.",
        language: "bash",
        code: "pwd\nls -la\nfind . -name '*.log' -type f\nps aux | grep nginx\nss -tulpn",
        tips: ["Read command docs before recursive operations.", "Quote paths that may contain spaces.", "Use least privilege for administration."],
      },
      {
        title: "Permissions",
        description: "Understand owner, group, and world permissions.",
        language: "bash",
        code: "chmod 640 app.log\nchown app:app app.log\nsudo systemctl status nginx",
        tips: ["Avoid chmod 777.", "Review systemd logs with journalctl.", "Keep secrets out of shell history."],
      },
    ],
    quiz: commonQuiz("Linux"),
  },
  {
    slug: "nmap-network-scanning",
    title: "Nmap Network Scanning",
    category: "Cybersecurity",
    description: "Authorized host discovery, service detection, script scans, timing, and reporting.",
    tags: ["Nmap", "Networking", "Security"],
    difficulty: "Intermediate",
    updated: "2026-06-29",
    related: ["common-ports", "dns-reference", "wireshark-packet-analysis"],
    sections: [
      {
        title: "Discovery and Services",
        description: "Run only against systems you own or have permission to test.",
        language: "bash",
        code: "nmap -sn 192.168.1.0/24\nnmap -sV -sC -oA scan-result 192.168.1.10\nnmap --top-ports 100 --reason example.com",
        tips: ["Document authorization and scope.", "Start gentle, then increase depth.", "Store results for comparison and remediation."],
      },
    ],
    quiz: commonQuiz("Nmap"),
  },
  {
    slug: "burp-suite-web-testing",
    title: "Burp Suite Web Testing",
    category: "Cybersecurity",
    description: "Proxy setup, repeater workflows, intruder restraint, auth testing, and reporting.",
    tags: ["Burp Suite", "OWASP", "Web Security"],
    difficulty: "Intermediate",
    updated: "2026-06-20",
    related: ["owasp-top-10", "sql-injection", "xss-reference"],
    sections: [
      {
        title: "Manual Testing Loop",
        description: "Capture a request, replay it in Repeater, and compare server behavior.",
        language: "http",
        code: "GET /account?id=42 HTTP/1.1\nHost: app.local\nCookie: session=...\nAccept: application/json",
        tips: ["Never test production without permission.", "Use project files for evidence.", "Prefer manual validation before automation."],
      },
    ],
    quiz: commonQuiz("Burp Suite"),
  },
  {
    slug: "wireshark-packet-analysis",
    title: "Wireshark Packet Analysis",
    category: "Cybersecurity",
    description: "Display filters, TCP streams, DNS inspection, TLS clues, and packet triage.",
    tags: ["Wireshark", "Packets", "Networking"],
    difficulty: "Intermediate",
    updated: "2026-06-14",
    related: ["dns-reference", "common-ports", "nmap-network-scanning"],
    sections: [
      {
        title: "Display Filters",
        description: "Narrow captures without modifying the original packet data.",
        language: "txt",
        code: "dns\nhttp.request\ntcp.port == 443\nip.addr == 10.0.0.5\ntcp.analysis.retransmission",
        tips: ["Capture only what policy allows.", "Use follow stream for conversations.", "Save filtered evidence separately."],
      },
    ],
    quiz: commonQuiz("Wireshark"),
  },
  {
    slug: "owasp-top-10",
    title: "OWASP Top 10",
    category: "Cybersecurity",
    description: "Modern web application risk categories with prevention patterns and review prompts.",
    tags: ["OWASP", "AppSec", "Security"],
    difficulty: "Beginner",
    updated: "2026-06-12",
    related: ["sql-injection", "xss-reference", "jwt-security"],
    sections: [
      {
        title: "Review Checklist",
        description: "Use this compact checklist during design and code review.",
        language: "txt",
        code: "Access control: deny by default\nInput validation: allow-list where possible\nSecrets: never commit or expose client-side\nLogging: security events without sensitive data\nDependencies: patched and pinned",
        tips: ["Threat model before implementation.", "Test authorization on every object boundary.", "Automate dependency scanning."],
      },
    ],
    quiz: commonQuiz("OWASP"),
  },
  {
    slug: "sql-queries",
    title: "SQL Queries",
    category: "Databases",
    description: "Selects, joins, indexes, aggregation, transactions, and safe query patterns.",
    tags: ["SQL", "Databases", "Postgres"],
    difficulty: "Beginner",
    updated: "2026-06-10",
    related: ["sql-injection", "python-essentials", "json-security"],
    sections: [
      {
        title: "Join and Aggregate",
        description: "Group data with explicit joins and useful aliases.",
        language: "sql",
        code: "SELECT u.name, COUNT(o.id) AS orders\nFROM users u\nLEFT JOIN orders o ON o.user_id = u.id\nWHERE u.active = true\nGROUP BY u.id, u.name\nORDER BY orders DESC;",
        tips: ["Use parameterized queries.", "Add indexes for repeated filters.", "Wrap multi-step writes in transactions."],
      },
    ],
    quiz: commonQuiz("SQL"),
  },
  {
    slug: "docker-compose",
    title: "Docker Compose",
    category: "DevOps",
    description: "Local service orchestration, networks, volumes, health checks, and deployment hygiene.",
    tags: ["Docker", "DevOps", "Containers"],
    difficulty: "Intermediate",
    updated: "2026-06-08",
    related: ["git-workflows", "cloud-deployment", "bash-linux"],
    sections: [
      {
        title: "Service Stack",
        description: "Define local app dependencies with health checks and isolated volumes.",
        language: "yaml",
        code: "services:\n  web:\n    build: .\n    ports: ['3000:3000']\n    depends_on: [db]\n  db:\n    image: postgres:16\n    environment:\n      POSTGRES_PASSWORD: localdev\n    volumes: ['db-data:/var/lib/postgresql/data']\nvolumes:\n  db-data:",
        tips: ["Do not bake secrets into images.", "Use small base images.", "Scan images before deployment."],
      },
    ],
    quiz: commonQuiz("Docker"),
  },
  {
    slug: "cloud-deployment",
    title: "Cloud Deployment",
    category: "Cloud",
    description: "Environment strategy, serverless functions, observability, rollbacks, and cost controls.",
    tags: ["Cloud", "Vercel", "AWS"],
    difficulty: "Intermediate",
    updated: "2026-06-04",
    related: ["docker-compose", "git-workflows", "jwt-security"],
    sections: [
      {
        title: "Release Checklist",
        description: "Ship cloud changes with repeatable validation.",
        language: "txt",
        code: "Build passes\nEnvironment variables configured\nMigrations reviewed\nRollback path known\nLogs, metrics, and alerts enabled",
        tips: ["Use preview deployments.", "Separate build-time and runtime secrets.", "Set budgets and alerting."],
      },
    ],
    quiz: commonQuiz("cloud deployment"),
  },
  {
    slug: "ai-prompting",
    title: "AI Prompt Engineering",
    category: "AI",
    description: "Prompt structure, evals, tool use, retrieval, safety constraints, and iteration loops.",
    tags: ["AI", "Prompting", "Agents"],
    difficulty: "Beginner",
    updated: "2026-06-02",
    related: ["python-essentials", "react-hooks", "json-security"],
    sections: [
      {
        title: "Task Prompt",
        description: "Give the model role, context, constraints, examples, and output shape.",
        language: "txt",
        code: "Role: Senior security reviewer\nContext: Reviewing a Node API route\nTask: Find auth and injection risks\nConstraints: cite file lines, avoid speculation\nOutput: findings ordered by severity",
        tips: ["Evaluate with realistic examples.", "Keep sensitive data out of prompts.", "Prefer structured outputs for automation."],
      },
    ],
    quiz: commonQuiz("AI prompting"),
  },
  {
    slug: "common-ports",
    title: "Common Ports",
    category: "Networking",
    description: "Memorize and investigate common TCP/UDP service ports with security notes.",
    tags: ["Ports", "Networking", "Security"],
    difficulty: "Beginner",
    updated: "2026-05-29",
    related: ["nmap-network-scanning", "dns-reference", "wireshark-packet-analysis"],
    sections: [
      {
        title: "High-Signal Ports",
        description: "Ports worth recognizing quickly during operations or testing.",
        language: "txt",
        code: "22 SSH\n53 DNS\n80 HTTP\n123 NTP\n443 HTTPS\n445 SMB\n5432 PostgreSQL\n6379 Redis\n8080 Alternate HTTP",
        tips: ["Open ports are context, not proof of risk.", "Confirm service versions.", "Firewall by intent, not convenience."],
      },
    ],
    quiz: commonQuiz("ports"),
  },
  {
    slug: "dns-reference",
    title: "DNS Reference",
    category: "Networking",
    description: "Record types, resolver behavior, TTLs, troubleshooting, and security controls.",
    tags: ["DNS", "Networking", "Cloud"],
    difficulty: "Beginner",
    updated: "2026-05-20",
    related: ["common-ports", "cloud-deployment", "wireshark-packet-analysis"],
    sections: [
      {
        title: "Records and Lookup",
        description: "Inspect the records most likely to break deploys and email.",
        language: "bash",
        code: "dig A example.com\ndig CNAME docs.example.com\ndig MX example.com\ndig TXT example.com",
        tips: ["Lower TTL before migrations.", "Use SPF, DKIM, and DMARC for mail.", "Avoid exposing internal hostnames."],
      },
    ],
    quiz: commonQuiz("DNS"),
  },
  {
    slug: "git-workflows",
    title: "Git Workflows",
    category: "DevOps",
    description: "Branching, commits, review, rebasing, bisecting, and recovery commands.",
    tags: ["Git", "DevOps", "GitHub"],
    difficulty: "Beginner",
    updated: "2026-05-16",
    related: ["docker-compose", "cloud-deployment", "react-hooks"],
    sections: [
      {
        title: "Daily Flow",
        description: "Keep changes understandable and easy to review.",
        language: "bash",
        code: "git switch -c feature/search\ngit status --short\ngit add app components lib\ngit commit -m \"Add search experience\"\ngit push -u origin feature/search",
        tips: ["Commit cohesive changes.", "Use pull requests for review.", "Never rewrite shared history casually."],
      },
    ],
    quiz: commonQuiz("Git"),
  },
  {
    slug: "jwt-security",
    title: "JWT Security",
    category: "Cybersecurity",
    description: "Token structure, claims, expiration, storage, verification, and common mistakes.",
    tags: ["JWT", "Security", "Auth"],
    difficulty: "Intermediate",
    updated: "2026-05-12",
    related: ["owasp-top-10", "cloud-deployment", "json-security"],
    sections: [
      {
        title: "Verification Rules",
        description: "Decode only for inspection; verify before trusting claims.",
        language: "txt",
        code: "Validate signature\nCheck issuer and audience\nEnforce expiration\nReject unexpected algorithms\nRotate keys safely",
        tips: ["Do not store long-lived tokens in localStorage for high-risk apps.", "Use httpOnly cookies where appropriate.", "Keep signing keys server-side."],
      },
    ],
    quiz: commonQuiz("JWT"),
  },
  {
    slug: "sql-injection",
    title: "SQL Injection",
    category: "Cybersecurity",
    description: "How injection happens, how to prevent it, and how to test responsibly.",
    tags: ["SQL Injection", "OWASP", "Databases"],
    difficulty: "Intermediate",
    updated: "2026-05-07",
    related: ["owasp-top-10", "sql-queries", "burp-suite-web-testing"],
    sections: [
      {
        title: "Prevention Pattern",
        description: "Use parameterized queries and avoid string-built SQL.",
        language: "ts",
        code: "const user = await db.query(\n  'SELECT id, email FROM users WHERE email = $1',\n  [email]\n);",
        tips: ["Validate input shape separately from query safety.", "Restrict database permissions.", "Log attacks without logging secrets."],
      },
    ],
    quiz: commonQuiz("SQL injection"),
  },
  {
    slug: "xss-reference",
    title: "XSS Reference",
    category: "Cybersecurity",
    description: "Stored, reflected, and DOM XSS prevention with encoding and CSP guidance.",
    tags: ["XSS", "OWASP", "Frontend"],
    difficulty: "Intermediate",
    updated: "2026-05-04",
    related: ["owasp-top-10", "javascript-modern", "burp-suite-web-testing"],
    sections: [
      {
        title: "Safe Rendering",
        description: "Prefer framework escaping and explicit sanitization for rich HTML.",
        language: "tsx",
        code: "export function Comment({ body }: { body: string }) {\n  return <p>{body}</p>;\n}",
        tips: ["Avoid dangerouslySetInnerHTML.", "Set a restrictive CSP.", "Sanitize markdown and rich text server-side."],
      },
    ],
    quiz: commonQuiz("XSS"),
  },
  {
    slug: "regex-reference",
    title: "Regex Reference",
    category: "Programming",
    description: "Character classes, groups, anchors, lookarounds, flags, and performance cautions.",
    tags: ["Regex", "JavaScript", "Validation"],
    difficulty: "Beginner",
    updated: "2026-04-26",
    related: ["javascript-modern", "python-essentials", "xss-reference"],
    sections: [
      {
        title: "Useful Patterns",
        description: "Treat regex as a parser for small patterns, not full languages.",
        language: "js",
        code: "const emailish = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\nconst slug = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;\nconst words = text.match(/\\b\\w+\\b/g) ?? [];",
        tips: ["Test against maliciously long inputs.", "Avoid catastrophic backtracking.", "Use named groups for clarity."],
      },
    ],
    quiz: commonQuiz("regex"),
  },
  {
    slug: "json-security",
    title: "JSON Security",
    category: "Programming",
    description: "Parsing, schema validation, serialization, secrets, and API boundary hardening.",
    tags: ["JSON", "API", "Security"],
    difficulty: "Beginner",
    updated: "2026-04-22",
    related: ["javascript-modern", "jwt-security", "sql-queries"],
    sections: [
      {
        title: "Parse Defensively",
        description: "JSON.parse can throw and parsed values still need validation.",
        language: "ts",
        code: "function parseJson(input: string) {\n  try {\n    return { ok: true, value: JSON.parse(input) };\n  } catch {\n    return { ok: false, error: 'Invalid JSON' };\n  }\n}",
        tips: ["Do not trust shape after parsing.", "Avoid logging complete payloads with secrets.", "Set request size limits."],
      },
    ],
    quiz: commonQuiz("JSON"),
  },
];

export const securityReferences = [
  { name: "Metasploit", description: "Exploit validation framework for authorized labs and controlled assessments.", icon: Wrench },
  { name: "MITRE ATT&CK", description: "Tactics and techniques knowledge base for detection and threat modeling.", icon: Cpu },
  { name: "Reverse Shell Generator", description: "Educational payload reference with safety warnings and lab-only context.", icon: Terminal },
  { name: "HTTP Status Codes", description: "Human-readable HTTP responses with debugging and security notes.", icon: Globe2 },
  { name: "Password Generator", description: "Generate strong local passwords with entropy guidance.", icon: KeyRound },
  { name: "Regex References", description: "Validate inputs with readable, tested regular expressions.", icon: Braces },
];

export const searchIndex = [
  ...cheatSheets.map((item) => ({
    type: "Cheat Sheet",
    title: item.title,
    description: item.description,
    href: `/cheatsheets/${item.slug}`,
    tags: item.tags,
  })),
  ...utilityTools.map((item) => ({
    type: "Utility",
    title: item.name,
    description: item.description,
    href: `/tools#${item.slug}`,
    tags: [item.category],
  })),
  ...categories.map((item) => ({
    type: "Category",
    title: item.name,
    description: item.description,
    href: `/#${item.slug}`,
    tags: [item.slug],
  })),
];
